import Head from "next/head";

import Slitting from "../components/slitting.js";
import Waterjet from "../components/waterjet.js";
import Stockholder from "../components/stockholder.js";
import Contact from "../components/contact.js";
import Header from "../components/header.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Helaxa | Slitting, Waterjet and stockholder</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="My page title" key="title" />
        <meta property="og:title" content="My page title" key="title" />
      </Head>

      <main className="">
        <Header />
        <Slitting />
        <Waterjet />
        <Stockholder />
        <Contact />
      </main>
    </div>
  );
}
